# This is a basic workflow to help you get started with Actions

name: Build and Package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup MsBuild
      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@v1

      # Setup NuGet
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2

      # Add NuGet Sources
      - name: Nuget Add Source
        run: nuget sources Add -Name "uxav" -Source https://nuget.pkg.github.com/uxav/index.json -username uxav -password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText

      # Restore packages
      - name: Restore Nuget Packages
        run: nuget restore Logging.sln

      # Build Solution
      - name: Build
        run: msbuild Logging.sln /p:Configuration=Release

      # Pack Nuget
      - name: Pack Nuget
        run: nuget pack UXAV.Logging/UXAV.Logging.csproj

      # Publish Nuget
      - name: Push generated package to GitHub registry
        run: nuget push *.nupkg -source "uxav"