# This is a basic workflow to help you get started with Actions

name: Test Build

on:
  pull_request:
  push:

env:
  PROJECT_NAME: UXAV.Logging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
          cache: true

      - name: Restore Nuget Packages
        run: dotnet restore ${{ env.PROJECT_NAME }}

      - name: Build
        run: dotnet build --configuration Release --no-restore ${{ env.PROJECT_NAME }}

      - name: Pack Nuget
        run: dotnet pack --configuration Release --no-build --output nupkgs ${{ env.PROJECT_NAME }}
          
