# This is a basic workflow to help you get started with Actions

name: Test Build

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

env:
  PROJECT_NAME: UXAV.Logging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup .NET Core
        id: setup-dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
          cache: true
          cache-dependency-path: "${{ env.PROJECT_NAME }}/packages.lock.json"

      - name: Check version number
        id: check-version
        if: github.event_name == 'push'
        run: |
          version=$(grep -o '<Version>.*</Version>' **/${{ env.PROJECT_NAME }}.csproj | sed 's/<Version>\(.*\)<\/Version>/\1/')
          versionTagToCheck="v$version"
          echo "Version tag to check is $versionTagToCheck"
          git fetch --tags
          tags=$(git tag --list)
          echo "Looking at tags:\n$tags"
          for tag in $tags; do
          if [[ "$tag" == "$versionTagToCheck" ]]; then
            echo "Version tag $versionTagToCheck exists"
            exit 1
          fi
          done
          echo "Version tag $versionTagToCheck does not exist"
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Restore nuget packages
        id: restore
        run: dotnet restore ${{ env.PROJECT_NAME }}

      - name: Build
        id: build
        run: dotnet build ${{ env.PROJECT_NAME }} -c Release -v m --no-restore

      - name: Pack
        id: pack
        run: dotnet pack ${{ env.PROJECT_NAME }} -c Release -v m --no-build --output nupkgs

      - name: Upload package to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}.${{ env.VERSION }}.nupkg
          path: nupkgs/${{ env.PROJECT_NAME}}.${{ env.VERSION }}.nupkg
