name: Test Build

on:
  push:
    branches: [ develop ]
    pull_request:
      branches: [ master ]

env:
  # This gets updated automatically
  VERSION: 0.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2

      - name: Restore Nuget Packages
        run: nuget restore Logging.sln

      - name: Build
        run: msbuild Logging.sln /p:Configuration=Release
      
      # Get version number of the new dll file
      - name: Set Version Number
        shell: powershell
        run: |
          $version = ./.github/scripts/GenerateVersionNumber.ps1 -path PaymentSenseAV/bin/Release/PaymentSenseAV.dll
          Write-Output "PS returned version: $version"
          Write-Output "::set-env name=VERSION::$version"

      - name: Write Version
        run: Write-Output "$($Env:VERSION)" | Out-File -FilePath "$($Env:GITHUB_HOME)\output\version.txt"
      
      # Upload the Version file as an artifact
      - name: Upload version.txt
        uses: actions/upload-artifact@v1
        with:
          name: Version
          path: ${{env.GITHUB_HOME}}\output\version.txt